# -*- coding: utf-8 -*-
# Deployment settings for Constructs.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/5.2/s3e/makefile_builder/mkb.py', 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/Constructs.mkb', '--deploy-only']
mkb = 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/Constructs.mkb'
mkf = ['c:\\marmalade\\5.2\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\5.2\\modules\\derbh\\derbh.mkf', 'c:\\marmalade\\5.2\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\5.2\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\5.2\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\5.2\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\5.2\\modules\\iwgraphics\\iwgraphics.mkf', 'c:\\marmalade\\5.2\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\5.2\\modules\\iwgxfont\\iwgxfont.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/data', '.', 0),
]

assets['GLES1'] = [
    ('C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/data/ConstructsResources-gles1.dz', 'ConstructsResources-gles1.dz', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Constructs'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Constructs'
    long_caption = 'Constructs'
    version = [0, 0, 1]
    config = ['C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/data/app.icf']
    data_dir = 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/data'
    linux_ext_lib = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Debug_Constructs_VC10_arm/Constructs.s3e',
                   'release' : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Release_Constructs_VC10_arm/Constructs.s3e',
                 },
         'arm_gcc' : {
                   'debug'   : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Debug_Constructs_VC10_gcc_arm/Constructs.s3e',
                   'release' : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Release_Constructs_VC10_gcc_arm/Constructs.s3e',
                 },
         'x86' : {
                   'debug'   : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Debug_Constructs_VC10_x86/Constructs.s86',
                   'release' : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Release_Constructs_VC10_x86/Constructs.s86',
                 },
         'mips_gcc' : {
                   'debug'   : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Debug_Constructs_VC10_gcc_mips/Constructs.so',
                   'release' : 'C:/Users/ET/Documents/Universal Story/Universal Story/jj/constructs/build_constructs_vc10/Release_Constructs_VC10_gcc_mips/Constructs.so',
                 },
        }
    assets = assets['GLES1']

default = DefaultConfig()
